# Generated by Django 5.0.6 on 2024-06-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("no", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, null=True)),
                ("description", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
