# Generated by Django 5.0.6 on 2024-06-02 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
