# Generated by Django 5.0.6 on 2024-06-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp", "0002_alter_task_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
