# Generated by Django 5.0.6 on 2024-06-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp", "0004_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
