# Generated by Django 5.0.6 on 2024-06-03 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp", "0005_remove_userprofile_user_userprofile_email_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
