# Generated by Django 5.0.6 on 2024-06-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp", "0007_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
